Update README.md
eclipse-ee4j/starter pull request #231
Opened 2023-03-25 21:21 UTC by ojuschugh1

Add instructions for IDE #116

2023-03-25 21:36 UTC, m-reza-rahman commented on README.md
> +Install Maven:
This should not be needed. Eclipse comes with it's own Maven.

2023-03-25 21:39 UTC, m-reza-rahman commented on README.md
> +Install the Maven Integration for Eclipse:
This should not be needed. For Jakarta EE projects, we should specify the Enterprise version of Eclipse.

2023-03-25 21:40 UTC, m-reza-rahman commented on README.md
> +Create a new Maven project:
These are generic instructions. Please provide instructions specific to our archetype.

2023-03-25 21:41 UTC, m-reza-rahman commented on README.md
> +Configure the Maven project:
This should not be needed. Eclipse will auto-detect this.

2023-03-25 21:43 UTC, m-reza-rahman commented on README.md
> +Build and run the project:
This is too generic. The information here should be specific to our archetype.

2023-03-25 21:43 UTC, m-reza-rahman requested changes
Please address comments before we can consider merging.

2023-03-26 17:21 UTC, ojuschugh1 commented
@m-reza-rahman  please review it I have added steps more specific now.
Thanks and Regards

2023-03-26 17:41 UTC, m-reza-rahman commented on README.md
> +## Instructions On How To Use Archetypes From An IDE Such As Eclipse
This is still basically generic instructions on how to create a Maven project in Eclipse using Archetypes. It really has nothing about our specific project. This needs to outline the specific steps for our project including what the user needs to do in order to move forward with the generated project. At the current trajectory, I estimate days of work before this PR is ready to merge. Please avoid frivolous PR updates and aim for quality as well as completeness. It needlessly consumed everyone's time.

2023-03-26 18:50 UTC, ojuschugh1 commented
Ok sir will surely be doing more research about it and adding it more in the comment section before the final PR :).
Thanks for giving me your time.It means alot to me :)

2023-03-26 19:10 UTC, m-reza-rahman commented
I am trying to do what I can. Please take the time to carefully/completely process feedback provided and take the PR out of draft status when it is really ready for meaningful review.

2023-03-26 20:24 UTC, m-reza-rahman commented on README.md
> +Open Eclipse and select "File > New > Other..." from the menu bar.
Selecting "Other" is unnecessary. Maven has been a top level choice in Eclipse IDE for some time now.

2023-03-26 20:26 UTC, m-reza-rahman commented on README.md
> +# If you are using an enterprise version of Eclipse for a Jakarta EE project, you can follow these steps to create a new Maven project with an archetype:
This should be explicit about what the setup pre-requisites are. Here is an example: https://github.com/eclipse-ee4j/cargotracker/wiki/Eclipse-IDE.

2023-03-26 20:30 UTC, m-reza-rahman commented on README.md
> +In the "Select an Archetype" dialog, click the "Add Archetype" button.
Why is "Add Archetype" needed here? Our archetype will already be in Maven Central or installed as a SNAPSHOT in the local repository.

2023-03-27 15:24 UTC, ojuschugh1 commented
Thanks for the help!

2023-03-27 15:24 UTC, closed without merging