[WIP] Fix #246
eclipse-ee4j/starter pull request #293
Opened 2024-01-10 18:32 UTC by yashTEF

WIP PR for #246 

This PR addresses changes required for fetching the header/footer html fragments from: https://jakarta.ee.

While the changes do the job of fetching the header and footer fragments, there are still some menu links
which have relative path as source which will need to be converted to absolute(refer: https://github.com/eclipse-ee4j/starter/issues/246#issuecomment-1875063434) for this PR to be successfully merged.

2024-01-10 18:40 UTC, yashTEF commented
> While the changes do the job of fetching the header and footer fragments, there are still some menu links which have relative path as source which will need to be converted to absolute(refer: [#246 (comment)](https://github.com/eclipse-ee4j/starter/issues/246#issuecomment-1875063434)) for this PR to be successfully merged.

@autumnfound, I can submit a patch to https://github.com/jakartaee/jakarta.ee for the changes required in the templates for you to review?

2024-01-10 19:11 UTC, autumnfound commented
> @autumnfound, I can submit a patch to https://github.com/jakartaee/jakarta.ee for the changes required in the templates for you to review?

If you feel comfortable submitting a patch, absolutely! Otherwise, you can create an issue and we can triage and take care of it in the near future as well.

2024-06-01 16:52 UTC, yashTEF commented
@kito99, this PR is functional and maybe reviewed now.

@m-reza-rahman while this PR addresses the issue of fetching the headers/footers,
I am not sure how the layout and styling for the UI are supposed to work as the existing starter UI available at: https://start.jakarta.ee is quite different to the above proposed.

2024-06-03 16:45 UTC, m-reza-rahman commented on ui/src/main/java/org/eclipse/starter/ui/FetchHtmlUtility.java
Why does this need to be done every time? It looks like this is static. Why can't be do this in the Maven build too?

2024-06-03 16:45 UTC, m-reza-rahman requested changes
Is this now ready to merge? If so, can you address the question?

2024-06-04 14:17 UTC, edburns commented on ui/src/main/java/org/eclipse/starter/ui/FetchHtmlUtility.java
This is my first time seeing this PR. My first impression is that using the JSF Facelets `<ui:include>` feature is an easier way to accomplish what the `FetchHtmlUtility` is doing.

At a very high level, using Java code to generate markup is an [anti-pattern](https://en.wikipedia.org/wiki/Anti-pattern). A more current (but certainly not the only) way to do it is to keep in XHTML as much as possible and use Expression Language elements in the XHTML to pull in the parts that need to be dynamic.

This is a StackOver Flow question that talks about this. https://stackoverflow.com/questions/8947425/how-to-conditionally-include-a-file-in-my-template-using-jsf-and-facelets

2024-06-04 14:18 UTC, edburns requested changes
https://github.com/eclipse-ee4j/starter/pull/293/files#r1626102027

2024-06-06 14:31 UTC, yashTEF commented on ui/src/main/java/org/eclipse/starter/ui/FetchHtmlUtility.java
There was some existing XHTML code present in the topbar.xhtml which was needed along with the html code fetched from the url, some parsing along with placing the code inside <ui:composition> tag made me think of the above approach as it was a bit straightforward but as Reza mentioned I did not take into the consideration the performance issue of doing the above repeatedly.

I'll try to find some out of the box feature present in maven plugins which does the above.

2025-03-16 16:45 UTC, m-reza-rahman commented
Just to provide a head's up, I will be working to resolve this long-standing issue in the next few weeks.

2025-03-18 19:15 UTC, m-reza-rahman commented
Resolved as discussed here: https://github.com/eclipse-ee4j/starter/issues/246.

2025-03-18 19:15 UTC, closed without merging