Add all positive cases for tomee
eclipse-ee4j/starter pull request #303
Opened 2024-06-24 17:42 UTC by jannahsherif

2024-06-25 09:19 UTC, jannahsherif commented on .github/workflows/nightly.yml
Ok will do

2024-06-27 13:24 UTC, jannahsherif commented
Hello I just committed my new changes. After reviewing the feedback I add docker support and added the deleted cases

2024-06-27 23:49 UTC, m-reza-rahman requested changes
Please order by SE version (starting with the lowest), runtime/none (alphabetic, starting with none), EE version (starting with the lowest), profile (full, web, core), and Docker (no, yes).

So like this:

* Run Archetype for EE 8 Web Profile, SE 8, Payara
* Run Archetype for EE 8 Web Profile, SE 8, Payara, with Docker

Please order your part and the file overall - including existing cases. Confusing to read and evaluate otherwise for me.

2024-07-01 21:20 UTC, m-reza-rahman commented
Please resolve conflicts with latest commits to master.

2024-07-02 14:42 UTC, jannahsherif commented
Hello I tried implement the reviews and organizing the cases correctly

2024-07-02 14:46 UTC, m-reza-rahman commented
At the bare minimum, the issue you need to resolve now are the conflicts before I can review again. Those will happen and are normal in a multi-developer project.

2024-07-02 15:22 UTC, jannahsherif commented
hi i reviewed the conflicts

2024-07-02 15:29 UTC, m-reza-rahman commented
OK. I will review if I have some time during the work week. Otherwise, may need to wait until the weekend.

2024-07-02 19:23 UTC, m-reza-rahman requested changes
Please double check ordering/duplication. It is still incorrect. Check the latest successful merges for reference if needed.

2024-07-04 19:27 UTC, m-reza-rahman requested changes
This PR should be focused on TomEE. Please remove changes related to WildFly.

2024-07-06 14:19 UTC, jannahsherif commented
In my latest commit "minor fixes" i only added the cases for tomee i did not change anything else in the original nighly

2024-07-07 21:36 UTC, m-reza-rahman commented on .github/workflows/nightly.yml
> +      - uses: actions/checkout@v4
Please pull the latest from master. This diff should disappear.

2024-07-07 21:36 UTC, m-reza-rahman commented on .github/workflows/nightly.yml
> +        uses: actions/setup-java@v4
Please pull the latest from master. This diff should disappear.

2024-07-07 21:36 UTC, m-reza-rahman commented on .github/workflows/nightly.yml
> +        uses: actions/cache@v4
Please pull the latest from master. This diff should disappear.

2024-07-07 21:36 UTC, m-reza-rahman commented on .github/workflows/nightly.yml
> +
Why is this white space change needed.

2024-07-07 21:37 UTC, m-reza-rahman commented on .github/workflows/nightly.yml
> +
Why is this white space change needed?

2024-07-07 21:37 UTC, m-reza-rahman commented on .github/workflows/nightly.yml
> +          docker build -t test-image app/wildfly/jakartaee-hello-world
Please remove this. This is not related to TomEE.

2024-07-07 21:38 UTC, m-reza-rahman commented on .github/workflows/nightly.yml
> +          docker build -t test-image app/wildfly/jakartaee-hello-world
Please remove this. This is not related to TomEE.

2024-07-07 21:38 UTC, m-reza-rahman commented on .github/workflows/nightly.yml
> +        uses: actions/setup-java@v4
Please pull the latest from master. This diff should disappear.

2024-07-07 21:38 UTC, m-reza-rahman commented on .github/workflows/nightly.yml
> +
Why is this white space change needed?

2024-07-07 21:39 UTC, m-reza-rahman commented on .github/workflows/nightly.yml
> +          docker build -t test-image app/wildfly/jakartaee-hello-world
Please remove this. This is not related to TomEE.

2024-07-07 21:39 UTC, m-reza-rahman commented on .github/workflows/nightly.yml
> +          docker build -t test-image app/wildfly/jakartaee-hello-world
Please remove this. This is not related to TomEE.

2024-07-07 21:39 UTC, m-reza-rahman commented on .github/workflows/nightly.yml
> +          docker build -t test-image app/wildfly/jakartaee-hello-world
Please remove this. This is not related to TomEE.

2024-07-07 21:39 UTC, m-reza-rahman commented on .github/workflows/nightly.yml
> +          docker build -t test-image app/wildfly/jakartaee-hello-world
Please remove this. This is not related to TomEE.

2024-07-07 21:39 UTC, m-reza-rahman commented on .github/workflows/nightly.yml
> +          docker build -t test-image app/wildfly/jakartaee-hello-world
Please remove this. This is not related to TomEE.

2024-07-07 21:40 UTC, m-reza-rahman commented on .github/workflows/nightly.yml
> +        uses: actions/setup-java@v4
Please pull the latest from master. This diff should disappear.

2024-07-07 21:40 UTC, m-reza-rahman commented on .github/workflows/nightly.yml
> +
Why is this white space change needed?

2024-07-07 21:40 UTC, m-reza-rahman commented on .github/workflows/nightly.yml
> +        uses: actions/cache@v4
Please pull the latest from master. This diff should disappear.

2024-07-07 21:41 UTC, m-reza-rahman commented on .github/workflows/nightly.yml
> +        uses: actions/setup-java@v4
Please pull the latest from master. This diff should disappear.

2024-07-07 21:41 UTC, m-reza-rahman commented on .github/workflows/nightly.yml
> +      - uses: actions/checkout@v4
Please pull the latest from master. This diff should disappear.

2024-07-07 21:41 UTC, m-reza-rahman commented on .github/workflows/nightly.yml
> +          docker build -t test-image app/wildfly/jakartaee-hello-world
Please remove this. This is not related to TomEE.

2024-07-07 21:41 UTC, m-reza-rahman commented on .github/workflows/nightly.yml
> +          docker build -t test-image app/wildfly/jakartaee-hello-world
Please remove this. This is not related to TomEE.

2024-07-07 21:41 UTC, m-reza-rahman commented on .github/workflows/nightly.yml
> +          docker build -t test-image app/wildfly/jakartaee-hello-world
Please remove this. This is not related to TomEE.

2024-07-07 21:42 UTC, m-reza-rahman commented on .github/workflows/nightly.yml
> +          docker build -t test-image app/wildfly/jakartaee-hello-world
Please remove this. This is not related to TomEE.

2024-07-07 21:42 UTC, m-reza-rahman commented on .github/workflows/nightly.yml
> +          docker build -t test-image app/wildfly/jakartaee-hello-world
Please remove this. This is not related to TomEE.

2024-07-07 21:45 UTC, m-reza-rahman requested changes
I have now added specific in-place feedback for you. Please address them. Then I can review hopefully one last time before merge.

2024-07-07 22:59 UTC, jannahsherif commented
Thank you for the detailed explanation! I resolved all the conflicts but I am running into a problem with the space changes. If i remove the extra space it highlights it in red. If I readd it, it shows one line red then the one after green. How can i get it not be red or green?

2024-07-07 23:26 UTC, m-reza-rahman commented
It looks honestly like you have some sync issues. What I suggest is closing this PR, saving aside your changes, forking fresh again, re-apply your changes, and then open a new PR. That might be easiest at this point.

2024-07-09 10:12 UTC, closed without merging