Add all positive cases for Glassfish runtime
eclipse-ee4j/starter pull request #304
Opened 2024-06-24 17:42 UTC by adan-jawad

2024-06-24 18:10 UTC, m-reza-rahman requested changes
This is organized incorrectly. At the top level, there should be two jobs: one for the Archetype and one for the UI. For the Archetype, things should first be organized by Java SE version, corresponding to invocations with that version. For each Java SE version, tests should then be organized by runtime, Jakarta EE version, profile then Docker flag.

2024-06-27 13:27 UTC, adan-jawad commented
Hello, I have added descriptions for docker support and organized the cases in the way specified. I have restored the old cases from the original file and have added my cases between the start and end comments for every java version for easy readability. I'll remove these comments once you review this.

2024-06-27 23:46 UTC, m-reza-rahman requested changes
Please order by SE version (starting with the lowest), runtime/none (alphabetic, starting with none), EE version (starting with the lowest), profile (full, web, core), and Docker (no, yes).

So like this:

* Run Archetype for EE 8 Web Profile, SE 8, Payara
* Run Archetype for EE 8 Web Profile, SE 8, Payara, with Docker

Where Docker is really not supported (a warning is generated by the Archetype), we should not treat that as a "positive case". That's a negative case we need to test for later. GlassFish currently does not support Docker.

Please order your part and the file overall - including existing cases. Confusing to read and evaluate otherwise for me.

2024-07-01 21:20 UTC, m-reza-rahman commented
Please resolve conflicts with latest commits to master.

2024-07-02 14:38 UTC, adan-jawad commented
I am a bit confused. Do I delete the cases where docker is not supported, or do I just remove that from the description?

2024-07-02 14:43 UTC, m-reza-rahman commented
For now, kindly remove the cases where Docker is not supported and set them aside. These need to be added later as explicitly tested negative cases.

2024-07-02 15:18 UTC, m-reza-rahman commented
Please resolve all merge conflicts.

2024-07-02 15:47 UTC, m-reza-rahman commented
I will review if I have some time during the work week. Otherwise, may need to wait until the weekend.

2024-07-02 15:52 UTC, adan-jawad commented
> I will review if I have some time during the work week. Otherwise, may need to wait until the weekend.

Sure.

2024-07-02 21:14 UTC, m-reza-rahman commented on .github/workflows/nightly.yml
> +          rm -rf app
Why is this needed?

2024-07-02 21:14 UTC, m-reza-rahman commented on .github/workflows/nightly.yml
> +      - name: Run Archetype for EE 8 Web Profile, SE 8, GlassFish
This is a duplicate. Why is it needed?

2024-07-02 21:15 UTC, m-reza-rahman commented on .github/workflows/nightly.yml
> +
Why was this added?

2024-07-02 21:16 UTC, m-reza-rahman commented on .github/workflows/nightly.yml
> +
Why was this added?

2024-07-02 21:17 UTC, m-reza-rahman commented on .github/workflows/nightly.yml
> +
Where are the SE 8 cases for GlassFish?

2024-07-02 21:22 UTC, m-reza-rahman requested changes
My guess is that this PR has some improper merge conflict resolution issues. Please re-inspect and fix.

2024-07-07 21:49 UTC, m-reza-rahman commented on .github/workflows/nightly.yml
> +      - uses: actions/checkout@v4
Please pull the latest from master. This diff should disappear.

2024-07-07 21:49 UTC, m-reza-rahman commented on .github/workflows/nightly.yml
> +        uses: actions/cache@v4
Please pull the latest from master. This diff should disappear.

2024-07-07 21:50 UTC, m-reza-rahman commented on .github/workflows/nightly.yml
> +        uses: actions/setup-java@v4
Please pull the latest from master. This diff should disappear.

2024-07-07 21:50 UTC, m-reza-rahman commented on .github/workflows/nightly.yml
> +        uses: actions/setup-java@v4
Please pull the latest from master. This diff should disappear.

2024-07-07 21:50 UTC, m-reza-rahman commented on .github/workflows/nightly.yml
> +      - uses: actions/checkout@v4
Please pull the latest from master. This diff should disappear.

2024-07-07 21:50 UTC, m-reza-rahman commented on .github/workflows/nightly.yml
> +        uses: actions/setup-java@v4
Please pull the latest from master. This diff should disappear.

2024-07-07 21:50 UTC, m-reza-rahman commented on .github/workflows/nightly.yml
> +        uses: actions/cache@v4
Please pull the latest from master. This diff should disappear.

2024-07-07 21:51 UTC, m-reza-rahman commented on .github/workflows/nightly.yml
> +
Why is this white space change needed?

2024-07-07 21:51 UTC, m-reza-rahman commented on .github/workflows/nightly.yml
> +
Why is this white space change needed?

2024-07-07 21:51 UTC, m-reza-rahman commented on .github/workflows/nightly.yml
> +
Why is this white space change needed?

2024-07-07 21:52 UTC, m-reza-rahman commented on .github/workflows/nightly.yml
> +
Why is this white space change needed?

2024-07-07 21:52 UTC, m-reza-rahman commented on .github/workflows/nightly.yml
> +        run: mvn clean package --file ui/pom.xml
Why is this white space change needed?

2024-07-07 21:52 UTC, m-reza-rahman commented on .github/workflows/nightly.yml
> +          docker build -t test-image app/wildfly/jakartaee-hello-world
Please remove this. This is not related to GlassFish.

2024-07-07 21:53 UTC, m-reza-rahman commented on .github/workflows/nightly.yml
> +        uses: actions/setup-java@v4
Please pull the latest from master. This diff should disappear.

2024-07-07 21:53 UTC, m-reza-rahman commented on .github/workflows/nightly.yml
> +          docker build -t test-image app/wildfly/jakartaee-hello-world
Please remove this. This is not related to GlassFish.

2024-07-07 21:53 UTC, m-reza-rahman commented on .github/workflows/nightly.yml
> +          docker build -t test-image app/wildfly/jakartaee-hello-world
Please remove this. This is not related to GlassFish.

2024-07-07 21:53 UTC, m-reza-rahman commented on .github/workflows/nightly.yml
> +          docker build -t test-image app/wildfly/jakartaee-hello-world
Please remove this. This is not related to GlassFish.

2024-07-07 21:53 UTC, m-reza-rahman commented on .github/workflows/nightly.yml
> +          docker build -t test-image app/wildfly/jakartaee-hello-world
Please remove this. This is not related to GlassFish.

2024-07-07 21:54 UTC, m-reza-rahman commented on .github/workflows/nightly.yml
> +          docker build -t test-image app/wildfly/jakartaee-hello-world
Please remove this. This is not related to GlassFish.

2024-07-07 21:54 UTC, m-reza-rahman commented on .github/workflows/nightly.yml
> +          docker build -t test-image app/wildfly/jakartaee-hello-world
Please remove this. This is not related to GlassFish.

2024-07-07 21:54 UTC, m-reza-rahman commented on .github/workflows/nightly.yml
> +          docker build -t test-image app/wildfly/jakartaee-hello-world
Please remove this. This is not related to GlassFish.

2024-07-07 21:54 UTC, m-reza-rahman commented on .github/workflows/nightly.yml
> +          docker build -t test-image app/wildfly/jakartaee-hello-world
Please remove this. This is not related to GlassFish.

2024-07-07 21:54 UTC, m-reza-rahman commented on .github/workflows/nightly.yml
> +          docker build -t test-image app/wildfly/jakartaee-hello-world
Please remove this. This is not related to GlassFish.

2024-07-07 21:54 UTC, m-reza-rahman commented on .github/workflows/nightly.yml
> +          docker build -t test-image app/wildfly/jakartaee-hello-world
Please remove this. This is not related to GlassFish.

2024-07-07 21:54 UTC, m-reza-rahman commented on .github/workflows/nightly.yml
> +          docker build -t test-image app/wildfly/jakartaee-hello-world
Please remove this. This is not related to GlassFish.

2024-07-07 21:57 UTC, m-reza-rahman requested changes
Please address specific in-place feedback. Then I can review hopefully one last time before merge.

2024-07-13 14:37 UTC, adan-jawad commented
Hello Reza, I am going to create a new pull request and I'm closing this one

2024-07-13 14:38 UTC, closed without merging