Add all positive cases for Open Liberty in nightly build
eclipse-ee4j/starter pull request #305
Opened 2024-06-24 17:45 UTC by mohamed-elzeni

2024-06-24 18:22 UTC, m-reza-rahman commented on .github/workflows/nightly.yml
> -      - name: Run Archetype for EE 8, SE 8
Why was this deleted? This is a legitimate test case.

2024-06-24 18:24 UTC, m-reza-rahman commented on .github/workflows/nightly.yml
> +      - name: Run Archetype for EE 9.1 Full Profile, SE 8, Open-liberty
Please fully describe the case. Is it using Docker or not? Also, please use "Open Liberty" instead of "Open-liberty".

2024-06-24 18:26 UTC, m-reza-rahman commented on .github/workflows/nightly.yml
> -      - name: Run Archetype for EE 8 Web Profile, SE 8, GlassFish
Please restore all unnecessarily deleted cases.

2024-06-24 18:28 UTC, m-reza-rahman requested changes
Please address all review comments.

2024-06-25 17:45 UTC, m-reza-rahman commented
I take it this is not ready for review again yet?

2024-06-26 04:07 UTC, mohamed-elzeni commented
Not yet, it needs still needs more work.

2024-06-26 09:51 UTC, m-reza-rahman commented
OK. Please take it out of draft mode when you think it is ready to merge or ask me explicitly to do an intermediate review of the draft.

2024-06-27 13:29 UTC, mohamed-elzeni commented
I have added descriptions for Docker support and restored unnecessarily deleted cases. Can you please review?

2024-06-27 23:43 UTC, m-reza-rahman requested changes
Please order by SE version (starting with the lowest), runtime/none (alphabetic, starting with none), EE version (starting with the lowest), profile (full, web, core), and Docker (no, yes).

So like this:

* Run Archetype for EE 8 Web Profile, SE 8, Payara
* Run Archetype for EE 8 Web Profile, SE 8, Payara, with Docker

Please order your part and the file overall - including existing cases. Confusing to read and evaluate otherwise for me.

2024-06-28 15:39 UTC, m-reza-rahman commented
Up to you. Either way is fine as long as it is consistent across the board.

2024-07-01 13:50 UTC, m-reza-rahman commented
Is this ready for review now?

2024-07-01 21:19 UTC, m-reza-rahman requested changes
Please resolve conflicts with latest commits to master.

2024-07-01 22:01 UTC, mohamed-elzeni commented
All conflicts have been resolved. I believe this is ready for review now.

2024-07-02 00:01 UTC, m-reza-rahman commented
Well done! Merging.

2024-07-02 00:01 UTC, merged