Add all positive cases for TomEE
eclipse-ee4j/starter pull request #312
Opened 2024-07-09 10:29 UTC by jannahsherif

2024-07-09 14:17 UTC, m-reza-rahman commented
This looks a lot better. I’ll review closely as soon as I can.

2024-07-09 15:11 UTC, jannahsherif commented
Thank you !

2024-07-09 15:20 UTC, m-reza-rahman commented on .github/workflows/nightly.yml
> +      - name: Run Archetype for EE 8 Web Profile, SE 8, TomEE, with Docker
This is a duplicate of the one above. Please fix the one above.

2024-07-09 15:24 UTC, m-reza-rahman commented on .github/workflows/nightly.yml
> +
This is a duplicate of the one above. Please fix the one above.

2024-07-09 15:26 UTC, m-reza-rahman requested changes
Please address review comments.

2024-07-10 00:32 UTC, jannahsherif commented
Thank you for the feedback, but i am not sure i understand where the duplicate is? One is with docker and one is without docker support

2024-07-10 00:37 UTC, m-reza-rahman commented
The duplicates are the commands themselves, not the labels. They are all asking for a Dockerfile to be generated.
  

 From: jannahsherif ***@***.***>Sent: Tuesday, July 9, 2024 8:32 PMTo: eclipse-ee4j/starter ***@***.***>Cc: Reza Rahman ***@***.***>; Comment ***@***.***>Subject: Re: [eclipse-ee4j/starter] Add all positive cases for TomEE (PR #312) 
Thank you for the feedback, but i am not sure i understand where the duplicate is? One is with docker and one is without docker support

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

2024-07-10 03:09 UTC, merged