Negative cases for tomee
eclipse-ee4j/starter pull request #323
Opened 2024-07-25 15:21 UTC by jannahsherif

2024-07-25 16:06 UTC, m-reza-rahman commented
Please resolve conflicts.

2024-07-25 16:16 UTC, jannahsherif commented
I just resolved them. I did SE 8 just to make sure i am going in the right direction

2024-07-26 15:43 UTC, m-reza-rahman commented on .github/workflows/nightly.yml
Looking at the TomEE validation: https://github.com/eclipse-ee4j/starter/blob/039a1ae96a28d43024fc347d97982ee4cda741f8/archetype/src/main/resources/META-INF/archetype-post-generate.groovy#L74, I see that the lack of EE 10 support negative test case (https://github.com/eclipse-ee4j/starter/blob/039a1ae96a28d43024fc347d97982ee4cda741f8/archetype/src/main/resources/META-INF/archetype-post-generate.groovy#L75) is missing. Please add that.

2024-07-26 15:50 UTC, m-reza-rahman commented on .github/workflows/nightly.yml
> +          ERROR_MESSAGE="TomEE requires Web Profile and Jakarta EE 8 or 9.1."
The error messages you need to check for will be from the Archetype, not the UI. Please look here: https://github.com/eclipse-ee4j/starter/blob/master/archetype/src/main/resources/META-INF/archetype-post-generate.groovy.

2024-07-26 15:50 UTC, m-reza-rahman commented on .github/workflows/nightly.yml
> +          ERROR_MESSAGE="TomEE requires Web Profile and Jakarta EE 8 or 9.1."
The error messages you need to check for will be from the Archetype, not the UI. Please look here: https://github.com/eclipse-ee4j/starter/blob/master/archetype/src/main/resources/META-INF/archetype-post-generate.groovy.

2024-07-26 15:51 UTC, m-reza-rahman commented on .github/workflows/nightly.yml
> +          ERROR_MESSAGE="TomEE requires Web Profile and Jakarta EE 8 or 9.1."
The error messages you need to check for will be from the Archetype, not the UI. Please look here: https://github.com/eclipse-ee4j/starter/blob/master/archetype/src/main/resources/META-INF/archetype-post-generate.groovy.

2024-07-26 15:59 UTC, m-reza-rahman requested changes
The error messages and use cases are not correct. They need to correspond to the Archetype validation. I suggest getting guidance from Tasnim and/or Elzeni.

2024-07-29 18:50 UTC, closed without merging