Negative Cases for TomEE nightly.yml
eclipse-ee4j/starter pull request #324
Opened 2024-07-29 19:44 UTC by jannahsherif

2024-07-29 19:53 UTC, jannahsherif commented
Elzeni helped me with groovy script and errors, hopefully this one is correct

2024-07-30 12:48 UTC, jannahsherif commented
Completed :)  thank you

2024-07-30 14:26 UTC, m-reza-rahman commented
Will look ASAP. On vacation, traveling.

2024-07-30 18:17 UTC, m-reza-rahman commented on .github/workflows/nightly.yml
> +      - name: Run Archetype for EE 9, SE 8, TomEE
This test should be using the Web profile. That is the only profile that TomEE supports. For Jakarta EE 9, it should also be using Java SE 11. TomEE 9 does not support Java SE 8.

2024-07-30 18:18 UTC, m-reza-rahman commented on .github/workflows/nightly.yml
There is a test missing for TomEE and the Core profile.

2024-07-30 18:25 UTC, m-reza-rahman requested changes
Please address review comments.

2024-07-30 21:40 UTC, jannahsherif commented
thank you for the feedback, I resolved the comments

2024-07-31 16:12 UTC, m-reza-rahman commented on .github/workflows/nightly.yml
> +      - name: Run Archetype for EE 8 Core Profile, SE 8, TomEE
You were right the first time. Since TomEE does not support EE 10 yet, we cannot meaningfully do this test. Let’s remove it. Thanks!

2024-07-31 16:15 UTC, m-reza-rahman commented on .github/workflows/nightly.yml
> +      - name: Run Archetype for EE 9 Web Profile, SE 8, TomEE
This is SE 11, not SE 8. TomEE 9 does not support Java SE 8.

2024-07-31 16:17 UTC, m-reza-rahman commented on .github/workflows/nightly.yml
> +      - name: Run Archetype for EE 9 Web Profile, SE 8, TomEE
This needs to be SE 11, not SE 8. TomEE 9 does not support SE 8.

2024-07-31 16:18 UTC, m-reza-rahman requested changes
Please address review comments.

2024-08-01 13:43 UTC, jannahsherif commented
I resolved the comments :)

2024-08-01 15:31 UTC, m-reza-rahman commented
This looks good now. I’ll try to take a closer look in the evening and hopefully merge.

2024-08-03 12:15 UTC, jannahsherif commented
ok per
fect

2024-08-03 15:10 UTC, merged